// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID     string `json:"id"`
	Text   string `json:"text"`
	Post   *Post  `json:"post"`
	Author *User  `json:"author"`
}

type Mutation struct {
}

type NewComment struct {
	Text     string `json:"text"`
	PostID   string `json:"postId"`
	AuthorID string `json:"authorId"`
}

type NewLike struct {
	UserID string `json:"userId"`
	PostID string `json:"postId"`
}

type NewPost struct {
	Title    string `json:"title"`
	Content  string `json:"content"`
	AuthorID string `json:"authorId"`
}

type NewUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Query struct {
}

type UpdateComment struct {
	Text *string `json:"text,omitempty"`
}

type UpdatePost struct {
	Title   *string `json:"title,omitempty"`
	Content *string `json:"content,omitempty"`
}

type UpdateUser struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}
